export const EXPENSE_DETAIL_CREATE_REQUEST = "EXPENSE_DETAIL_CREATE_REQUEST";
export const EXPENSE_DETAIL_CREATE_SUCCESS = "EXPENSE_DETAIL_CREATE_SUCCESS";
export const EXPENSE_DETAIL_CREATE_FAILURE = "EXPENSE_DETAIL_CREATE_FAILURE";

export const EXPENSE_LISTS_CREATE_REQUEST = "EXPENSE_LISTS_CREATE_REQUEST";
export const EXPENSE_LISTS_CREATE_SUCCESS = "EXPENSE_LISTS_CREATE_SUCCESS";
export const EXPENSE_LISTS_CREATE_FAILURE = "EXPENSE_LISTS_CREATE_FAILURE";

export const EXPENSE_DETAIL_UPDATE_REQUEST = "EXPENSE_DETAIL_UPDATE_REQUEST";
export const EXPENSE_DETAIL_UPDATE_SUCCESS = "EXPENSE_DETAIL_UPDATE_SUCCESS";
export const EXPENSE_DETAIL_UPDATE_FAILURE = "EXPENSE_DETAIL_UPDATE_FAILURE";

export const EXPENSE_DETAIL_DELETE_REQUEST = "EXPENSE_DETAIL_DELETE_REQUEST";
export const EXPENSE_DETAIL_DELETE_SUCCESS = "EXPENSE_DETAIL_DELETE_SUCCESS";
export const EXPENSE_DETAIL_DELETE_FAILURE = "EXPENSE_DETAIL_DELETE_FAILURE";
