export const FEEDBACK_CREATE_REQUEST = "FEEDBACK_CREATE_REQUEST";
export const FEEDBACK_CREATE_SUCCESS = "FEEDBACK_CREATE_SUCCESS";
export const FEEDBACK_CREATE_FAILURE = "FEEDBACK_CREATE_FAILURE";

export const FEEDBACK_LISTS_REQUEST = "FEEDBACK_LISTS_REQUEST";
export const FEEDBACK_LISTS_SUCCESS = "FEEDBACK_LISTS_SUCCESS";
export const FEEDBACK_LISTS_FAILURE = "FEEDBACK_LISTS_FAILURE";
