export const GROCERY_ITEM_CREATE_REQUEST = "GROCERY_ITEM_CREATE_REQUEST";
export const GROCERY_ITEM_CREATE_SUCCESS = "GROCERY_ITEM_CREATE_SUCCESS";
export const GROCERY_ITEM_CREATE_FAILURE = "GROCERY_ITEM_CREATE_FAILURE";

export const GROCERY_LISTS_CREATE_REQUEST = "GROCERY_LISTS_CREATE_REQUEST";
export const GROCERY_LISTS_CREATE_SUCCESS = "GROCERY_LISTS_CREATE_SUCCESS";
export const GROCERY_LISTS_CREATE_FAILURE = "GROCERY_LISTS_CREATE_FAILURE";

export const GROCERY_ITEM_UPDATE_REQUEST = "GROCERY_ITEM_UPDATE_REQUEST";
export const GROCERY_ITEM_UPDATE_SUCCESS = "GROCERY_ITEM_UPDATE_SUCCESS";
export const GROCERY_ITEM_UPDATE_FAILURE = "GROCERY_ITEM_UPDATE_FAILURE";

export const GROCERY_ITEM_DELETE_REQUEST = "GROCERY_ITEM_DELETE_REQUEST";
export const GROCERY_ITEM_DELETE_SUCCESS = "GROCERY_ITEM_DELETE_SUCCESS";
export const GROCERY_ITEM_DELETE_FAILURE = "GROCERY_ITEM_DELETE_FAILURE";
