export const SALARY_REPORTS_CREATE_REQUEST = "SALARY_REPORTS_CREATE_REQUEST";
export const SALARY_REPORTS_CREATE_SUCCESS = "SALARY_REPORTS_CREATE_SUCCESS";
export const SALARY_REPORTS_CREATE_FAILURE = "SALARY_REPORTS_CREATE_FAILURE";

export const EXPENSE_REPORTS_CREATE_REQUEST = "EXPENSE_REPORTS_CREATE_REQUEST";
export const EXPENSE_REPORTS_CREATE_SUCCESS = "EXPENSE_REPORTS_CREATE_SUCCESS";
export const EXPENSE_REPORTS_CREATE_FAILURE = "EXPENSE_REPORTS_CREATE_FAILURE";

export const GROCERY_REPORTS_CREATE_REQUEST = "GROCERY_REPORTS_CREATE_REQUEST";
export const GROCERY_REPORTS_CREATE_SUCCESS = "GROCERY_REPORTS_CREATE_SUCCESS";
export const GROCERY_REPORTS_CREATE_FAILURE = "GROCERY_REPORTS_CREATE_FAILURE";
